 I’m @Kinkykha
- 👀 I’m interested in ...
- 🌱 I’m currently learning how to speak Spanish...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...

<!---
Kinkykha/Kinkykha is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
